# Generated by Django 5.2.8 on 2026-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking_Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
